### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/output_dir/freesurfer/sub-01/mri/orig/001.mgz'

### ISSUE THREAD

**Issue by sebastientourbier** [sebastientourbier/multiscalebrainparcellator#9]
**Description**

When the multiscalebrainparcellator has already been run on a subject but need to be reprocess, symlink to orig/001.mgz is broken

**Steps to reproduce the error**

1. Run a first time the multiscalebrainparcellator
2. Delete the derivatives/cmp and derivatives/nipype folders but keep the derivatives/freesurfer (we do not want to run reconall for about 10 hours again)
3. Run a second time the multiscalebrainparcellator 

**Command line error**
```bash
docker run -v '/media/localadmin/HagmannHDD/Seb/ds005:/bids_dir' -v '/media/localadmin/HagmannHDD/Seb/ds005/derivatives:/output_dir' -it sebastientourbier/multiscalebrainparcellator:v1.0.1-beta0 '/bids_dir' '/output_dir' participant --participant_label 01 --skip_bids_validator --thalamic_nuclei --hippocampal_subfields --brainstem_structures
BIDS dataset: /bids_dir
MAIN INFO: /bids_dir/code/license.txt Freesurfer license found will be used
MAIN WARNING: the specified number of cores (None) should be greater to 0
MAIN INFO: Maximal number of cores set to the maximal number of available cores (12)
MAIN INFO: Default isotropic resolution for resampling: 1.0
Traceback (most recent call last):
  File "/opt/conda/envs/py27msbparc/bin/multiscalebrainparcellator_bidsapp_entrypointscript", line 189, in <module>
    total_size += os.path.getsize(fp)
  File "/opt/conda/envs/py27msbparc/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/output_dir/freesurfer/sub-01/mri/orig/001.mgz'
```

**Comment by sebastientourbier** [comment]
**Solution**
001.mgz should be deleted. It will be regenerated by the multiscalebrainparcellator
